package com.hmt.graduate.paper.pojo;

import java.io.Serializable;
import java.util.Date;

public class Patient implements Serializable {
    private Integer id;
    private String name;
    private Integer age;

    private Integer sex;

    private String adress;

    private Date createDate;

    private String allergy;
    private String familyDisease;

    private String symptom;

    private Date illnessTime;

    private String degree;

    private String phoneNo;

    private String hispitalNo;

    private String primaryDiagnosis;

    private String historyDisease;

    private String historyAnesthesia;

    private String marriage;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getAdress() {
        return adress;
    }

    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getAllergy() {
        return allergy;
    }


    public void setAllergy(String allergy) {
        this.allergy = allergy == null ? null : allergy.trim();
    }

    public String getFamilyDisease() {
        return familyDisease;
    }

    public void setFamilyDisease(String familyDisease) {
        this.familyDisease = familyDisease == null ? null : familyDisease.trim();
    }

    public String getSymptom() {
        return symptom;
    }


    public void setSymptom(String symptom) {
        this.symptom = symptom == null ? null : symptom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.illness_time
     *
     * @return the value of patients.illness_time
     *
     * @mbg.generated
     */
    public Date getIllnessTime() {
        return illnessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.illness_time
     *
     * @param illnessTime the value for patients.illness_time
     *
     * @mbg.generated
     */
    public void setIllnessTime(Date illnessTime) {
        this.illnessTime = illnessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.degree
     *
     * @return the value of patients.degree
     *
     * @mbg.generated
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.degree
     *
     * @param degree the value for patients.degree
     *
     * @mbg.generated
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.phone_no
     *
     * @return the value of patients.phone_no
     *
     * @mbg.generated
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.phone_no
     *
     * @param phoneNo the value for patients.phone_no
     *
     * @mbg.generated
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.hispital_no
     *
     * @return the value of patients.hispital_no
     *
     * @mbg.generated
     */
    public String getHispitalNo() {
        return hispitalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.hispital_no
     *
     * @param hispitalNo the value for patients.hispital_no
     *
     * @mbg.generated
     */
    public void setHispitalNo(String hispitalNo) {
        this.hispitalNo = hispitalNo == null ? null : hispitalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.primary_diagnosis
     *
     * @return the value of patients.primary_diagnosis
     *
     * @mbg.generated
     */
    public String getPrimaryDiagnosis() {
        return primaryDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.primary_diagnosis
     *
     * @param primaryDiagnosis the value for patients.primary_diagnosis
     *
     * @mbg.generated
     */
    public void setPrimaryDiagnosis(String primaryDiagnosis) {
        this.primaryDiagnosis = primaryDiagnosis == null ? null : primaryDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.history_disease
     *
     * @return the value of patients.history_disease
     *
     * @mbg.generated
     */
    public String getHistoryDisease() {
        return historyDisease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.history_disease
     *
     * @param historyDisease the value for patients.history_disease
     *
     * @mbg.generated
     */
    public void setHistoryDisease(String historyDisease) {
        this.historyDisease = historyDisease == null ? null : historyDisease.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.history_anesthesia
     *
     * @return the value of patients.history_anesthesia
     *
     * @mbg.generated
     */
    public String getHistoryAnesthesia() {
        return historyAnesthesia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.history_anesthesia
     *
     * @param historyAnesthesia the value for patients.history_anesthesia
     *
     * @mbg.generated
     */
    public void setHistoryAnesthesia(String historyAnesthesia) {
        this.historyAnesthesia = historyAnesthesia == null ? null : historyAnesthesia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.marriage
     *
     * @return the value of patients.marriage
     *
     * @mbg.generated
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.marriage
     *
     * @param marriage the value for patients.marriage
     *
     * @mbg.generated
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage == null ? null : marriage.trim();
    }

}