package com.hmt.graduate.paper.pojo;

import java.io.Serializable;
import java.util.Date;

public class Patient implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.adress
     *
     * @mbg.generated
     */
    private String adress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.allergy
     *
     * @mbg.generated
     */
    private String allergy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.family_disease
     *
     * @mbg.generated
     */
    private String familyDisease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.symptom
     *
     * @mbg.generated
     */
    private String symptom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.illness_time
     *
     * @mbg.generated
     */
    private Date illnessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.degree
     *
     * @mbg.generated
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.phone_no
     *
     * @mbg.generated
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.hispital_no
     *
     * @mbg.generated
     */
    private String hispitalNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.primary_diagnosis
     *
     * @mbg.generated
     */
    private String primaryDiagnosis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.history_disease
     *
     * @mbg.generated
     */
    private String historyDisease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.history_anesthesia
     *
     * @mbg.generated
     */
    private String historyAnesthesia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patients.marriage
     *
     * @mbg.generated
     */
    private String marriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patients
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.id
     *
     * @return the value of patients.id
     *
     * @mbg.generated
     */
=======
    private Integer id;
    private String idCard;
    private String name;
    private Integer age;

    private Integer sex;

    private String adress;

    private Date createDate;

    private String allergy;
    private String familyDisease;

    private String symptom;

    private Date illnessTime;

    private String degree;

    private String phoneNo;

    private String hispitalNo;

    private String primaryDiagnosis;

    private String historyDisease;

    private String historyAnesthesia;

    private String marriage;

    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.id
     *
     * @param id the value for patients.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.name
     *
     * @return the value of patients.name
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getName() {
        return name;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.name
     *
     * @param name the value for patients.name
     *
     * @mbg.generated
     */

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.age
     *
     * @return the value of patients.age
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public Integer getAge() {
        return age;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.age
     *
     * @param age the value for patients.age
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setAge(Integer age) {
        this.age = age;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.sex
     *
     * @return the value of patients.sex
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public Integer getSex() {
        return sex;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.sex
     *
     * @param sex the value for patients.sex
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setSex(Integer sex) {
        this.sex = sex;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.adress
     *
     * @return the value of patients.adress
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getAdress() {
        return adress;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.adress
     *
     * @param adress the value for patients.adress
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.create_date
     *
     * @return the value of patients.create_date
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public Date getCreateDate() {
        return createDate;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.create_date
     *
     * @param createDate the value for patients.create_date
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.allergy
     *
     * @return the value of patients.allergy
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getAllergy() {
        return allergy;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.allergy
     *
     * @param allergy the value for patients.allergy
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setAllergy(String allergy) {
        this.allergy = allergy == null ? null : allergy.trim();
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.family_disease
     *
     * @return the value of patients.family_disease
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getFamilyDisease() {
        return familyDisease;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.family_disease
     *
     * @param familyDisease the value for patients.family_disease
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setFamilyDisease(String familyDisease) {
        this.familyDisease = familyDisease == null ? null : familyDisease.trim();
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.symptom
     *
     * @return the value of patients.symptom
     *
     * @mbg.generated
     */
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getSymptom() {
        return symptom;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.symptom
     *
     * @param symptom the value for patients.symptom
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setSymptom(String symptom) {
        this.symptom = symptom == null ? null : symptom.trim();
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.illness_time
     *
     * @return the value of patients.illness_time
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public Date getIllnessTime() {
        return illnessTime;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.illness_time
     *
     * @param illnessTime the value for patients.illness_time
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setIllnessTime(Date illnessTime) {
        this.illnessTime = illnessTime;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.degree
     *
     * @return the value of patients.degree
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getDegree() {
        return degree;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.degree
     *
     * @param degree the value for patients.degree
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.phone_no
     *
     * @return the value of patients.phone_no
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getPhoneNo() {
        return phoneNo;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.phone_no
     *
     * @param phoneNo the value for patients.phone_no
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.hispital_no
     *
     * @return the value of patients.hispital_no
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getHispitalNo() {
        return hispitalNo;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.hispital_no
     *
     * @param hispitalNo the value for patients.hispital_no
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setHispitalNo(String hispitalNo) {
        this.hispitalNo = hispitalNo == null ? null : hispitalNo.trim();
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.primary_diagnosis
     *
     * @return the value of patients.primary_diagnosis
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getPrimaryDiagnosis() {
        return primaryDiagnosis;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.primary_diagnosis
     *
     * @param primaryDiagnosis the value for patients.primary_diagnosis
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setPrimaryDiagnosis(String primaryDiagnosis) {
        this.primaryDiagnosis = primaryDiagnosis == null ? null : primaryDiagnosis.trim();
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.history_disease
     *
     * @return the value of patients.history_disease
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getHistoryDisease() {
        return historyDisease;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.history_disease
     *
     * @param historyDisease the value for patients.history_disease
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setHistoryDisease(String historyDisease) {
        this.historyDisease = historyDisease == null ? null : historyDisease.trim();
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.history_anesthesia
     *
     * @return the value of patients.history_anesthesia
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getHistoryAnesthesia() {
        return historyAnesthesia;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.history_anesthesia
     *
     * @param historyAnesthesia the value for patients.history_anesthesia
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setHistoryAnesthesia(String historyAnesthesia) {
        this.historyAnesthesia = historyAnesthesia == null ? null : historyAnesthesia.trim();
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patients.marriage
     *
     * @return the value of patients.marriage
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public String getMarriage() {
        return marriage;
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patients.marriage
     *
     * @param marriage the value for patients.marriage
     *
     * @mbg.generated
     */
=======

>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
    public void setMarriage(String marriage) {
        this.marriage = marriage == null ? null : marriage.trim();
    }

<<<<<<< HEAD
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Patient other = (Patient) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getAdress() == null ? other.getAdress() == null : this.getAdress().equals(other.getAdress()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getAllergy() == null ? other.getAllergy() == null : this.getAllergy().equals(other.getAllergy()))
            && (this.getFamilyDisease() == null ? other.getFamilyDisease() == null : this.getFamilyDisease().equals(other.getFamilyDisease()))
            && (this.getSymptom() == null ? other.getSymptom() == null : this.getSymptom().equals(other.getSymptom()))
            && (this.getIllnessTime() == null ? other.getIllnessTime() == null : this.getIllnessTime().equals(other.getIllnessTime()))
            && (this.getDegree() == null ? other.getDegree() == null : this.getDegree().equals(other.getDegree()))
            && (this.getPhoneNo() == null ? other.getPhoneNo() == null : this.getPhoneNo().equals(other.getPhoneNo()))
            && (this.getHispitalNo() == null ? other.getHispitalNo() == null : this.getHispitalNo().equals(other.getHispitalNo()))
            && (this.getPrimaryDiagnosis() == null ? other.getPrimaryDiagnosis() == null : this.getPrimaryDiagnosis().equals(other.getPrimaryDiagnosis()))
            && (this.getHistoryDisease() == null ? other.getHistoryDisease() == null : this.getHistoryDisease().equals(other.getHistoryDisease()))
            && (this.getHistoryAnesthesia() == null ? other.getHistoryAnesthesia() == null : this.getHistoryAnesthesia().equals(other.getHistoryAnesthesia()))
            && (this.getMarriage() == null ? other.getMarriage() == null : this.getMarriage().equals(other.getMarriage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getAdress() == null) ? 0 : getAdress().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getAllergy() == null) ? 0 : getAllergy().hashCode());
        result = prime * result + ((getFamilyDisease() == null) ? 0 : getFamilyDisease().hashCode());
        result = prime * result + ((getSymptom() == null) ? 0 : getSymptom().hashCode());
        result = prime * result + ((getIllnessTime() == null) ? 0 : getIllnessTime().hashCode());
        result = prime * result + ((getDegree() == null) ? 0 : getDegree().hashCode());
        result = prime * result + ((getPhoneNo() == null) ? 0 : getPhoneNo().hashCode());
        result = prime * result + ((getHispitalNo() == null) ? 0 : getHispitalNo().hashCode());
        result = prime * result + ((getPrimaryDiagnosis() == null) ? 0 : getPrimaryDiagnosis().hashCode());
        result = prime * result + ((getHistoryDisease() == null) ? 0 : getHistoryDisease().hashCode());
        result = prime * result + ((getHistoryAnesthesia() == null) ? 0 : getHistoryAnesthesia().hashCode());
        result = prime * result + ((getMarriage() == null) ? 0 : getMarriage().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patients
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append(", sex=").append(sex);
        sb.append(", adress=").append(adress);
        sb.append(", createDate=").append(createDate);
        sb.append(", allergy=").append(allergy);
        sb.append(", familyDisease=").append(familyDisease);
        sb.append(", symptom=").append(symptom);
        sb.append(", illnessTime=").append(illnessTime);
        sb.append(", degree=").append(degree);
        sb.append(", phoneNo=").append(phoneNo);
        sb.append(", hispitalNo=").append(hispitalNo);
        sb.append(", primaryDiagnosis=").append(primaryDiagnosis);
        sb.append(", historyDisease=").append(historyDisease);
        sb.append(", historyAnesthesia=").append(historyAnesthesia);
        sb.append(", marriage=").append(marriage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
=======
>>>>>>> 778539cb5552fe79a32abd6b761a7bd62c004977
}