--本项目数据库脚本：包括系统表，业务表
一,系统表
CREATE TABLE `SURGERY_BF_ESTIMATE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `PATIENT_ID` BIGINT(20) NOT NULL COMMENT '患者表id',
  `AGE` INT(3) NOT NULL COMMENT '年龄',
  `SEX` CHAR(1) NOT NULL COMMENT '性别',
  `EDU_YEAR` INT(3) NOT NULL COMMENT '受教育年限',
  `SURGERY_HIS` INT(1) DEFAULT NULL COMMENT '大手术史',
  `BRAIN_HIS` INT(1) NOT NULL COMMENT '脑部疾病',
  `DEPARTMENT` INT(1) DEFAULT NULL COMMENT '日常休闲活动情况',
  `SURGERY_BF_ILLNESS` INT(1) DEFAULT NULL COMMENT '术前疾病情况',
  `HOME_WORK` INT(1) DEFAULT NULL COMMENT '家务',
  `PLAY_PK` INT(1) DEFAULT NULL COMMENT '玩牌',
  `PLAY_CHESS` INT(1) DEFAULT NULL COMMENT '玩象棋',
  `READ_PAPER` INT(1) DEFAULT NULL COMMENT '读报纸',
  `MON_EXCETS` INT(1) DEFAULT NULL COMMENT '晨练',
  `PLAY_KID` INT(1) DEFAULT NULL COMMENT '带小孩',
  `TRAVEL` INT(1) DEFAULT NULL COMMENT '旅行',
  `GXB_ILLNESS` INT(1) DEFAULT NULL COMMENT '冠心病',
  `GXY_ILLNESS` INT(1) DEFAULT NULL COMMENT '高血压病',
  `TNB_ILLNESS` INT(1) DEFAULT NULL COMMENT '糖尿病',
  `LUNG_ILLNESS` INT(1) DEFAULT NULL COMMENT '肺部感染',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8 COMMENT='术前评估';




二,业务表

三,脚本语句
